### ISSUE TITLE
Wow trying to delete this, I think I solved something

### ISSUE THREAD

**Issue by psql** [javierarce/tumblr-liked-photos-export#18]

**Comment by psql** [comment]
Hey Javier, I get this error when trying your latest:
```
Traceback (most recent call last):
	3: from export.rb:145:in `<main>'
	2: from export.rb:106:in `download'
	1: from export.rb:41:in `get_liked_count'
export.rb:41:in `[]': no implicit conversion of String into Integer (TypeError)
```
Am I doing something stupid?

**Comment by javierarce** [comment]
Hi, @psql… no, it probably was my fault. 

I've pushed a couple of changes to show the URL that the script is using to download the likes and also fixed a problem with the input arguments of the script. Can you try again?

**Comment by garciadiego769** [comment]
Hi @javierarce,
I'm getting the same error:  `export.rb:42:in `[]': no implicit conversion of String into Integer (TypeError)`

**Comment by javierarce** [comment]
@garciadiego769 this could mean that the call to the API was unauthorized (maybe you didn't paste the API key correctly?).

If you download the last version and run it again, it'll print a URL in the terminal. Open the URL in a browser and see if there's an error message.

**Comment by psql** [comment]
@javierarce awesome, looks like we're back in business!!!
