### ISSUE TITLE
Unhandled 404 response

### ISSUE THREAD

**Issue by Unknow0059** [javierarce/tumblr-liked-photos-export#31]
Upon running `ruby.exe export.rb` I got this:

> Error: no implicit conversion of String into Integer
> Error: ["export.rb:61:in `[]'", "export.rb:61:in `get_liked_count'", "export.rb:130:in `start'", "export.rb:179:in `<main>'"]

If I print `parsed_response` with `puts parsed_response.inspec` on line 62 this is the result:
> {"meta"=>{"status"=>404, "msg"=>"Not Found"}, "response"=>[], "errors"=>[{"title"=>"Not Found", "code"=>0, "detail"=>"Minor hiccup. Try again."}]}

**Comment by Unknow0059** [comment]
`export.rb` tried exporting a blog that does not exist because the first letter of `TUMBLR_USERNAME`'s string was capitalized.

Still, it would be nice if the user was notified of this.
